services:
  - type: web
    name: fluxflow-studio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: HF_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
